type = "card"
title = "Academic Service"
# description = "Reviewer for several international journals."

[[items]]
title = "Reviewer for several international journals, including Journal of Intelligent Manufacturing, Scientific Reports, and Discover Applied Sciences."
