[site]
title = "何国华"
description = "广东工业大学博士生个人主页。"
last_updated = "2026年6月26日"

[author]
name = "何国华"
title = "博士生"
institution = "广东工业大学"

[social]
email = "hegh1511@163.com"
phone = "18723576304"
google_scholar = "https://scholar.google.com.hk/citations?hl=zh-CN&user=bg8m4UcAAAAJ&view_op=list_works&gmla=AP6z3OZ3uND666QS8OGU9puOoFaca5Z-tkYc9Af_hroMYu00Gax-G96L4CT79pYCFXN5dO2rmtUNsSBZQdGJ6NLK8QvELcvHp1iEOUtM-q8"
location = "广州，中国"
location_details = [
  "广东工业大学（大学城校区），",
  "工学楼 714 室"
]

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "「求知·治学」"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "「躬行·授业」"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "「载誉·前行」"
type = "page"
target = "awards"
href = "/awards"

# [[navigation]]
# title = "服务"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
